import React from 'react'

const PrivacyPolicy = () => {
  return (
    <div>
        <h2 className='text-2xl font-bold'>Privacy Policy</h2>
        <h3 className='text-xl font-semibold my-2'>INFORMATION GATHERING:</h3>
        <p className='my-4'>
            WIBA Gallery does not collect any type of personal information, nor does it collect files within the user's device that do not want to be stored, nor through cookies nor does it collect usage data generated by the application. WIBA Gallery chooses to offer the user excellent security and reliability for the storage of their images. The only thing needed to access our platform is a Google account.
        </p>

        <h3 className='text-xl font-semibold my-2'>IMAGE SECURITY:</h3>
        <p className='my-4'>
            The images that the user stores in our cloud is not shared with anyone, any other user or any third party who wishes to obtain this information. The stored images are simply accessible only to the user who uploaded this information.
        </p>

        <h3 className='text-xl font-semibold my-2'>WHERE THE IMAGES ARE STORED:</h3>
        <p className='my-4'>
            Images are stored in storage provided by Firebase, called Firebase Storage. This storage is provided by Google's cloud database, called Google Cloud Storage. Firebase always promises a secure connection for transfers made as well as providing login security through Firebase Authentication.
        </p>

    </div>
  )
}

export default PrivacyPolicy;